name: Build publish and test a public NPM package

on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repo
        uses: actions/checkout@v3

      - name: Autodetect and set-up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Documentate tools version 
        run: |
          echo -n 'Node version  ' && node -v
          echo -n 'NPM version  ' && npm -v

      - name: Clone workflows repo to get npmrc 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: bluealba/workflows-public
          path: pipeline/

      - name: Render npmrc file
        uses: nowactions/envsubst@v1
        with:
          input: /home/runner/work/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}/pipeline/files/bluealba/publish_npmrc
          output: ./.npmrc
        env:
          BA_NPMJS_AUTH_TOKEN : ${{ secrets.BA_NPMJS_AUTH_TOKEN }}

      - name: Install dependencies
        run: |
          cat .npmrc
          npm install

      - name: Test service 
        run: npm run test --if-present

      - name: Build service 
        run: npm run build --if-present

      - name: Create release package
        if: contains(github.ref ,'refs/heads/release') || contains(github.ref ,'refs/heads/hotfix') || contains(github.ref ,'refs/heads/master') || contains(github.ref ,'refs/heads/main')
        run: npm pack

      - name: Publish package
        if: contains(github.ref ,'refs/heads/release') || contains(github.ref ,'refs/heads/hotfix') || contains(github.ref ,'refs/heads/master') || contains(github.ref ,'refs/heads/main')
        run: |
          npm publish